flake8 setting

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -40,18 +40,17 @@ jobs:
     - name: Linting code with flake8
       uses: py-actions/flake8@latest
 
-  #   - name: Lint with flake8
-  #     id: flake8
-  #     continue-on-error: true
-  #     run: |
-  #       # fail if there are any flake8 errors
-  #       flake8 . --count --max-complexity=15 --max-line-length=127 --statistics
+    - name: Lint with flake8
+      id: flake8
+      continue-on-error: true
+      run: |
+        flake8 . --count --max-complexity=15 --max-line-length=127 --statistics
 
-  #   # - name: Check if 'Lint with flake8' step failed
-  #   #   if: steps.flake8.outcome != 'success'
-  #   #   run: |
-  #   #    echo "flake8 fails"
-  #   #    exit 1
+    - name: Check if 'Lint with flake8' step failed
+      if: steps.flake8.outcome != 'success'
+      run: |
+       echo "flake8 fails"
+       exit 1
       
   #   # - name: Security check report artifacts
   #   #   run: |
